name: cibuild
on:
  push

jobs:
  myci:
    runs-on: ubuntu-latest
    steps:
      - uses: quenktechnologies/.github/actions/node/build@master
      - run: npm test                 # run tests (configured to use jest-junit reporter)
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Mocha            # Name of the check run which will be created
          path: results.json    # Path to test results
          reporter: mocha-json        # Format of test results
